/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog

import (
	"encoding/json"
	"fmt"
)

// ListStreamWidgetDefinitionSource Source from which to query items to display in the stream.
type ListStreamWidgetDefinitionSource string

// List of ListStreamWidgetDefinitionSource
const (
	LISTSTREAMWIDGETDEFINITIONSOURCE_ISSUE_STREAM ListStreamWidgetDefinitionSource = "issue_stream"
	LISTSTREAMWIDGETDEFINITIONSOURCE_LOGS_STREAM  ListStreamWidgetDefinitionSource = "logs_stream"
)

var allowedListStreamWidgetDefinitionSourceEnumValues = []ListStreamWidgetDefinitionSource{
	"issue_stream",
	"logs_stream",
}

func (w *ListStreamWidgetDefinitionSource) GetAllowedValues() []ListStreamWidgetDefinitionSource {
	return allowedListStreamWidgetDefinitionSourceEnumValues
}

func (v *ListStreamWidgetDefinitionSource) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ListStreamWidgetDefinitionSource(value)
	for _, existing := range allowedListStreamWidgetDefinitionSourceEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ListStreamWidgetDefinitionSource", value)
}

// NewListStreamWidgetDefinitionSourceFromValue returns a pointer to a valid ListStreamWidgetDefinitionSource
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewListStreamWidgetDefinitionSourceFromValue(v string) (*ListStreamWidgetDefinitionSource, error) {
	ev := ListStreamWidgetDefinitionSource(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ListStreamWidgetDefinitionSource: valid values are %v", v, allowedListStreamWidgetDefinitionSourceEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ListStreamWidgetDefinitionSource) IsValid() bool {
	for _, existing := range allowedListStreamWidgetDefinitionSourceEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ListStreamWidgetDefinitionSource value
func (v ListStreamWidgetDefinitionSource) Ptr() *ListStreamWidgetDefinitionSource {
	return &v
}

type NullableListStreamWidgetDefinitionSource struct {
	value *ListStreamWidgetDefinitionSource
	isSet bool
}

func (v NullableListStreamWidgetDefinitionSource) Get() *ListStreamWidgetDefinitionSource {
	return v.value
}

func (v *NullableListStreamWidgetDefinitionSource) Set(val *ListStreamWidgetDefinitionSource) {
	v.value = val
	v.isSet = true
}

func (v NullableListStreamWidgetDefinitionSource) IsSet() bool {
	return v.isSet
}

func (v *NullableListStreamWidgetDefinitionSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListStreamWidgetDefinitionSource(val *ListStreamWidgetDefinitionSource) *NullableListStreamWidgetDefinitionSource {
	return &NullableListStreamWidgetDefinitionSource{value: val, isSet: true}
}

func (v NullableListStreamWidgetDefinitionSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListStreamWidgetDefinitionSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
