/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog

import (
	"encoding/json"
	"fmt"
)

// ListStreamQuery Updated list stream widget.
type ListStreamQuery struct {
	DataSource ListStreamWidgetDefinitionSource `json:"data_source"`
	// Widget query.
	QueryString string `json:"query_string"`
}

// NewListStreamQuery instantiates a new ListStreamQuery object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListStreamQuery(dataSource ListStreamWidgetDefinitionSource, queryString string) *ListStreamQuery {
	this := ListStreamQuery{}
	this.DataSource = dataSource
	this.QueryString = queryString
	return &this
}

// NewListStreamQueryWithDefaults instantiates a new ListStreamQuery object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListStreamQueryWithDefaults() *ListStreamQuery {
	this := ListStreamQuery{}
	var dataSource ListStreamWidgetDefinitionSource = LISTSTREAMWIDGETDEFINITIONSOURCE_ISSUE_STREAM
	this.DataSource = dataSource
	return &this
}

// GetDataSource returns the DataSource field value
func (o *ListStreamQuery) GetDataSource() ListStreamWidgetDefinitionSource {
	if o == nil {
		var ret ListStreamWidgetDefinitionSource
		return ret
	}

	return o.DataSource
}

// GetDataSourceOk returns a tuple with the DataSource field value
// and a boolean to check if the value has been set.
func (o *ListStreamQuery) GetDataSourceOk() (*ListStreamWidgetDefinitionSource, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DataSource, true
}

// SetDataSource sets field value
func (o *ListStreamQuery) SetDataSource(v ListStreamWidgetDefinitionSource) {
	o.DataSource = v
}

// GetQueryString returns the QueryString field value
func (o *ListStreamQuery) GetQueryString() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QueryString
}

// GetQueryStringOk returns a tuple with the QueryString field value
// and a boolean to check if the value has been set.
func (o *ListStreamQuery) GetQueryStringOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QueryString, true
}

// SetQueryString sets field value
func (o *ListStreamQuery) SetQueryString(v string) {
	o.QueryString = v
}

func (o ListStreamQuery) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data_source"] = o.DataSource
	}
	if true {
		toSerialize["query_string"] = o.QueryString
	}
	return json.Marshal(toSerialize)
}

func (o *ListStreamQuery) UnmarshalJSON(bytes []byte) (err error) {
	required := struct {
		DataSource  *ListStreamWidgetDefinitionSource `json:"data_source"`
		QueryString *string                           `json:"query_string"`
	}{}
	all := struct {
		DataSource  ListStreamWidgetDefinitionSource `json:"data_source"`
		QueryString string                           `json:"query_string"`
	}{}
	err = json.Unmarshal(bytes, &required)
	if err != nil {
		return err
	}
	if required.DataSource == nil {
		return fmt.Errorf("Required field data_source missing")
	}
	if required.QueryString == nil {
		return fmt.Errorf("Required field query_string missing")
	}
	err = json.Unmarshal(bytes, &all)
	if err != nil {
		return err
	}
	o.DataSource = all.DataSource
	o.QueryString = all.QueryString
	return nil
}

type NullableListStreamQuery struct {
	value *ListStreamQuery
	isSet bool
}

func (v NullableListStreamQuery) Get() *ListStreamQuery {
	return v.value
}

func (v *NullableListStreamQuery) Set(val *ListStreamQuery) {
	v.value = val
	v.isSet = true
}

func (v NullableListStreamQuery) IsSet() bool {
	return v.isSet
}

func (v *NullableListStreamQuery) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListStreamQuery(val *ListStreamQuery) *NullableListStreamQuery {
	return &NullableListStreamQuery{value: val, isSet: true}
}

func (v NullableListStreamQuery) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListStreamQuery) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
