/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * API version: 1.0
 * Contact: support@datadoghq.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog

import (
	"encoding/json"
)

// FastlyServiceTags Fastly tags to associate each metric to.
type FastlyServiceTags struct {
	// A list of tags(key:value), seperated by commas, to assign to each Fastly metric.
	ServiceTags string `json:"service_tags"`
}

// NewFastlyServiceTags instantiates a new FastlyServiceTags object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFastlyServiceTags(serviceTags string) *FastlyServiceTags {
	this := FastlyServiceTags{}
	this.ServiceTags = serviceTags
	return &this
}

// NewFastlyServiceTagsWithDefaults instantiates a new FastlyServiceTags object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFastlyServiceTagsWithDefaults() *FastlyServiceTags {
	this := FastlyServiceTags{}
	return &this
}

// GetServiceTags returns the ServiceTags field value
func (o *FastlyServiceTags) GetServiceTags() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceTags
}

// GetServiceTagsOk returns a tuple with the ServiceTags field value
// and a boolean to check if the value has been set.
func (o *FastlyServiceTags) GetServiceTagsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceTags, true
}

// SetServiceTags sets field value
func (o *FastlyServiceTags) SetServiceTags(v string) {
	o.ServiceTags = v
}

func (o FastlyServiceTags) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["service_tags"] = o.ServiceTags
	}
	return json.Marshal(toSerialize)
}

type NullableFastlyServiceTags struct {
	value *FastlyServiceTags
	isSet bool
}

func (v NullableFastlyServiceTags) Get() *FastlyServiceTags {
	return v.value
}

func (v *NullableFastlyServiceTags) Set(val *FastlyServiceTags) {
	v.value = val
	v.isSet = true
}

func (v NullableFastlyServiceTags) IsSet() bool {
	return v.isSet
}

func (v *NullableFastlyServiceTags) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFastlyServiceTags(val *FastlyServiceTags) *NullableFastlyServiceTags {
	return &NullableFastlyServiceTags{value: val, isSet: true}
}

func (v NullableFastlyServiceTags) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFastlyServiceTags) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
