/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * API version: 1.0
 * Contact: support@datadoghq.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog

import (
	"encoding/json"
)

// FastlyServiceAccount Fastly service account.
type FastlyServiceAccount struct {
	// Your service account to associate with.
	ServiceAccount string `json:"service_account"`
}

// NewFastlyServiceAccount instantiates a new FastlyServiceAccount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFastlyServiceAccount(serviceAccount string) *FastlyServiceAccount {
	this := FastlyServiceAccount{}
	this.ServiceAccount = serviceAccount
	return &this
}

// NewFastlyServiceAccountWithDefaults instantiates a new FastlyServiceAccount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFastlyServiceAccountWithDefaults() *FastlyServiceAccount {
	this := FastlyServiceAccount{}
	return &this
}

// GetServiceAccount returns the ServiceAccount field value
func (o *FastlyServiceAccount) GetServiceAccount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceAccount
}

// GetServiceAccountOk returns a tuple with the ServiceAccount field value
// and a boolean to check if the value has been set.
func (o *FastlyServiceAccount) GetServiceAccountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceAccount, true
}

// SetServiceAccount sets field value
func (o *FastlyServiceAccount) SetServiceAccount(v string) {
	o.ServiceAccount = v
}

func (o FastlyServiceAccount) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["service_account"] = o.ServiceAccount
	}
	return json.Marshal(toSerialize)
}

type NullableFastlyServiceAccount struct {
	value *FastlyServiceAccount
	isSet bool
}

func (v NullableFastlyServiceAccount) Get() *FastlyServiceAccount {
	return v.value
}

func (v *NullableFastlyServiceAccount) Set(val *FastlyServiceAccount) {
	v.value = val
	v.isSet = true
}

func (v NullableFastlyServiceAccount) IsSet() bool {
	return v.isSet
}

func (v *NullableFastlyServiceAccount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFastlyServiceAccount(val *FastlyServiceAccount) *NullableFastlyServiceAccount {
	return &NullableFastlyServiceAccount{value: val, isSet: true}
}

func (v NullableFastlyServiceAccount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFastlyServiceAccount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
